version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000" # Agent communication
    volumes:
      - jenkins:/var/jenkins_home # Persistent data storage
    networks:
      - jenkins-network

volumes:
  jenkins:
    driver: local

networks:
  jenkins-network:
    driver: bridge